let {
  PORT,
  MONGO_URI,
  JWT_SECRET,
  NODE_ENV,
  ORIGIN_URL,
  // PROD_PORT,
  // PROD_MONGO_URI,
  // PROD_JWT_SECRET,
  // PROD_ORIGIN_URL,
} = process.env;

const IN_PROD = NODE_ENV == "production";

if (IN_PROD) {
  PORT = PORT;
  MONGO_URI = MONGO_URI;
  JWT_SECRET = JWT_SECRET;
  ORIGIN_URL = ORIGIN_URL;
}

module.exports = { PORT, MONGO_URI, JWT_SECRET, ORIGIN_URL, NODE_ENV, IN_PROD };
